name = "fortran_parser"
license = "MIT"
author = "Dr Stuart Midgley"
copyright = "Copyright (c) 2020 Dr Stuart Midgley"
description = "A math function parser written entirely in fortran"
homepage = "https://github.com/sdm900/fortran_parser"
keywords = ["parser"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[library]
source-dir = "src"

[install]
library = true